export const TEMAS = [
{id:'comb',titulo:'Combinatória e Triângulo de Pascal',icone:'layout-grid',dif:'Médio',duracao:'50 min',grad:'linear-gradient(135deg,#14b8a6,#0f766e)',
desc:'Princípio fundamental da contagem, arranjos, combinações e as propriedades do Triângulo de Pascal.',
video:{id:'f0OjyQhITv0',titulo:"Análise combinatória — arranjo, permutação e combinação",canal:"Sandro Curió"},
dicaFacil:"Pergunta-chave: a ordem importa? Se sim (códigos, filas, passwords) usa arranjos/permutações. Se não (grupos, comissões) usa combinações. Conta passo a passo com o princípio multiplicativo.",

teoria:[
'O princípio fundamental da contagem diz-nos que, se uma escolha pode ser feita de $m$ maneiras e, para cada uma delas, outra escolha pode ser feita de $n$ maneiras, então as duas escolhas em sequência podem ser feitas de $m\\times n$ maneiras. É a base de toda a combinatória.',
'Quando a ordem dos elementos importa e não há repetição, usamos arranjos: $^nA_p$ conta as sequências de $p$ elementos distintos escolhidos entre $n$. Se a ordem não importa, usamos combinações: $^nC_p$ conta os subconjuntos de $p$ elementos. A pergunta-chave é sempre: «trocar a ordem dá um caso novo?»',
'O Triângulo de Pascal organiza os valores de $^nC_p$: a linha $n$ contém $^nC_0,\\ ^nC_1,\\dots,\\ ^nC_n$. Cada linha é simétrica ($^nC_p={^nC_{n-p}}$), a soma dos seus $n+1$ elementos é $2^n$ e cada elemento é a soma dos dois que estão por cima (propriedade de Pascal).'],
formulas:[
{n:'Fatorial',t:'$$n! = n\\times(n-1)\\times\\dots\\times 2\\times 1$$'},
{n:'Arranjos sem repetição',t:'$$^nA_p=\\frac{n!}{(n-p)!}$$'},
{n:'Arranjos com repetição',t:'$$^nA\'_p=n^p$$'},
{n:'Combinações',t:'$$^nC_p=\\frac{n!}{p!\\,(n-p)!}$$'},
{n:'Soma da linha n do Triângulo',t:'$$\\sum_{p=0}^{n}{^nC_p}=2^n$$'},
{n:'Propriedade de Pascal',t:'$$^nC_p+{^nC_{p+1}}={^{n+1}C_{p+1}}$$'}],
exemplo:{e:'Com os algarismos de 0 a 9, quantos códigos de 4 algarismos todos diferentes começam por um algarismo ímpar?',passos:[
{t:'Escolher o primeiro algarismo',c:'Tem de ser ímpar: $1, 3, 5, 7$ ou $9$ — há $5$ escolhas possíveis.'},
{t:'Escolher os restantes três',c:'Sobram $9$ algarismos e a ordem importa: $^9A_3=9\\times 8\\times 7=504$ maneiras.'},
{t:'Aplicar o princípio da contagem',c:'Multiplicam-se as escolhas: $5\\times 504=2520$ códigos possíveis.'}]},
erros:[
{e:'Usar combinações quando a ordem importa (códigos, palavras, filas).',c:'Se trocar a ordem cria um caso novo, são arranjos: $^nA_p$.'},
{e:'Confundir a linha $n$ do Triângulo de Pascal com «$n$ elementos».',c:'A linha $n$ tem $n+1$ elementos, de $^nC_0$ a $^nC_n$.'},
{e:'Esquecer restrições (algarismo inicial não pode ser 0, elementos juntos, etc.).',c:'Trata primeiro a restrição e só depois conta o resto.'}]},
{id:'prob',titulo:'Probabilidades',icone:'dices',dif:'Médio',duracao:'55 min',grad:'linear-gradient(135deg,#38bdf8,#0369a1)',
desc:'Lei de Laplace, probabilidade da união e da interseção, probabilidade condicionada e independência.',
video:{id:'iNCkGogNtKI',titulo:"Probabilidade — aprende em 13 min",canal:"Sandro Curió"},
dicaFacil:"Probabilidade = casos que queres ÷ casos possíveis (Laplace). Na união, soma e subtrai a interseção para não contar duas vezes. Em condicionada, o que vem depois da barra vira o novo total.",

teoria:[
'Num espaço de resultados equiprováveis aplica-se a Lei de Laplace: a probabilidade de um acontecimento é o quociente entre o número de casos favoráveis e o número de casos possíveis. O valor está sempre entre $0$ e $1$.',
'Para a união vale sempre $P(A\\cup B)=P(A)+P(B)-P(A\\cap B)$ — subtrai-se a interseção para não a contar duas vezes. Se $A$ e $B$ são incompatíveis, $P(A\\cap B)=0$ e a fórmula reduz-se à soma.',
'A probabilidade condicionada $P(A\\mid B)$ é a probabilidade de $A$ sabendo que $B$ aconteceu: restringimos o universo a $B$. Dois acontecimentos são independentes quando $P(A\\cap B)=P(A)\\times P(B)$, ou seja, saber que $B$ ocorreu não altera a probabilidade de $A$.'],
formulas:[
{n:'Lei de Laplace',t:'$$P(A)=\\frac{\\text{n.º de casos favoráveis}}{\\text{n.º de casos possíveis}}$$'},
{n:'Acontecimento contrário',t:'$$P(\\overline{A})=1-P(A)$$'},
{n:'União',t:'$$P(A\\cup B)=P(A)+P(B)-P(A\\cap B)$$'},
{n:'Probabilidade condicionada',t:'$$P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}$$'},
{n:'Independência',t:'$$P(A\\cap B)=P(A)\\times P(B)$$'}],
exemplo:{e:'Numa turma há 12 raparigas e 8 rapazes. Usam óculos 5 raparigas e 2 rapazes. Escolhe-se um aluno ao acaso e verifica-se que usa óculos. Qual é a probabilidade de ser rapariga?',passos:[
{t:'Identificar o que se pede',c:'Pede-se $P(R\\mid O)$ — probabilidade de ser rapariga sabendo que usa óculos.'},
{t:'Restringir o universo',c:'Sabendo que usa óculos, o universo passa a ser os $5+2=7$ alunos com óculos.'},
{t:'Aplicar Laplace no novo universo',c:'Das 7 pessoas com óculos, 5 são raparigas: $P(R\\mid O)=\\frac{5}{7}$.'}]},
erros:[
{e:'Calcular $P(A\\cup B)$ somando sem subtrair $P(A\\cap B)$.',c:'Só se soma diretamente quando os acontecimentos são incompatíveis.'},
{e:'Confundir $P(A\\mid B)$ com $P(B\\mid A)$.',c:'O acontecimento depois da barra é o que se sabe que aconteceu (o novo universo).'},
{e:'Assumir independência sem a verificar.',c:'Independência exige $P(A\\cap B)=P(A)\\times P(B)$ — tem de se confirmar.'}]},
{id:'func',titulo:'Funções afins e quadráticas',icone:'chart-line',dif:'Fácil',duracao:'45 min',grad:'linear-gradient(135deg,#34d399,#047857)',
desc:'Declive e ordenada na origem, zeros, vértice da parábola, concavidade e contradomínio.',
video:{id:'ZpW9Xb5iyt4',titulo:"Função do 2.º grau — fácil e rápido",canal:"Sandro Curió"},
dicaFacil:"Afim: reta com declive m = (y2−y1)/(x2−x1). Quadrática: parábola; zeros pela fórmula; vértice em x=−b/(2a). Olha o sinal de a para saber se tem máximo ou mínimo.",

teoria:[
'Uma função afim escreve-se $f(x)=mx+b$: o declive $m$ mede a inclinação (positivo → crescente, negativo → decrescente) e $b$ é a ordenada na origem. Por dois pontos $(x_1,y_1)$ e $(x_2,y_2)$ o declive calcula-se por $m=\\frac{y_2-y_1}{x_2-x_1}$.',
'Uma função quadrática $f(x)=ax^2+bx+c$ tem por gráfico uma parábola: concavidade voltada para cima se $a>0$, para baixo se $a<0$. Os zeros obtêm-se pela fórmula resolvente e o vértice tem abcissa $x_v=-\\frac{b}{2a}$ (ponto médio dos zeros, quando existem).',
'O vértice determina o extremo da função: mínimo se $a>0$, máximo se $a<0$. Daí sai o contradomínio: por exemplo, com máximo $y_v$, o contradomínio é $\\left]-\\infty,\\,y_v\\right]$. A forma $f(x)=a(x-h)^2+k$ mostra o vértice $(h,k)$ diretamente.'],
formulas:[
{n:'Função afim',t:'$$f(x)=mx+b$$'},
{n:'Declive por dois pontos',t:'$$m=\\frac{y_2-y_1}{x_2-x_1}$$'},
{n:'Fórmula resolvente',t:'$$x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}$$'},
{n:'Vértice da parábola',t:'$$x_v=-\\frac{b}{2a},\\qquad y_v=f(x_v)$$'},
{n:'Forma canónica',t:'$$f(x)=a(x-h)^2+k,\\quad V=(h,k)$$'}],
exemplo:{e:'Estude a função $f(x)=x^2-6x+5$: zeros, vértice e contradomínio.',passos:[
{t:'Calcular os zeros',c:'Pela fórmula resolvente: $x=\\frac{6\\pm\\sqrt{36-20}}{2}=\\frac{6\\pm 4}{2}$, logo $x=1$ ou $x=5$.'},
{t:'Determinar o vértice',c:'$x_v=-\\frac{-6}{2}=3$ e $y_v=f(3)=9-18+5=-4$. Vértice: $(3,-4)$.'},
{t:'Concluir o contradomínio',c:'Como $a=1>0$, a concavidade está voltada para cima e o mínimo é $-4$: $D\'_f=[-4,+\\infty[$.'}]},
erros:[
{e:'Trocar o sinal do declive ou de $b$ ao ler o gráfico.',c:'Reta a descer → $m<0$; onde a reta corta o eixo $Oy$ é $b$.'},
{e:'Trocar as coordenadas do vértice.',c:'Primeiro calcula-se $x_v=-\\frac{b}{2a}$, depois $y_v=f(x_v)$.'},
{e:'Dar o contradomínio com o sentido errado.',c:'$a>0$ → mínimo → $[y_v,+\\infty[$; $a<0$ → máximo → $]-\\infty,y_v]$.'}]},
{id:'explog',titulo:'Exponenciais e logaritmos',icone:'trending-up',dif:'Difícil',duracao:'60 min',grad:'linear-gradient(135deg,#fbbf24,#b45309)',
desc:'Função exponencial, definição de logaritmo, propriedades operatórias e resolução de equações.',
video:{id:'tR6S4dz6UGA',titulo:"Aprende logaritmo em 8 minutos",canal:"Sandro Curió"},
dicaFacil:"Logaritmo é o expoente: log_a(x)=y significa a^y=x. Em equações, passa tudo para a mesma base e iguala expoentes. No fim confirma que o argumento do log é positivo.",

teoria:[
'A função exponencial $f(x)=a^x$ (com $a>0$, $a\\neq 1$) é sempre positiva: o gráfico nunca toca o eixo $Ox$. É crescente se $a>1$ e decrescente se $0<a<1$.',
'O logaritmo é a operação inversa: $\\log_a x = y \\iff a^y=x$. Só existem logaritmos de números positivos — o domínio de $\\log_a x$ é $]0,+\\infty[$. Casos especiais: $\\log_a 1=0$ e $\\log_a a=1$.',
'As propriedades operatórias transformam produtos em somas, quocientes em diferenças e potências em produtos. Para resolver equações, o método habitual é escrever ambos os membros na mesma base ou aplicar a definição de logaritmo, verificando sempre o domínio no fim.'],
formulas:[
{n:'Definição de logaritmo',t:'$$\\log_a x = y \\iff a^y = x$$'},
{n:'Logaritmo do produto',t:'$$\\log_a(xy)=\\log_a x+\\log_a y$$'},
{n:'Logaritmo do quociente',t:'$$\\log_a\\frac{x}{y}=\\log_a x-\\log_a y$$'},
{n:'Logaritmo da potência',t:'$$\\log_a x^p = p\\log_a x$$'},
{n:'Mudança de base',t:'$$\\log_a x=\\frac{\\ln x}{\\ln a}$$'}],
exemplo:{e:'Resolva, em $\\mathbb{R}$, a equação $5\\cdot 2^x = 40$.',passos:[
{t:'Isolar a exponencial',c:'Dividindo ambos os membros por 5: $2^x = 8$.'},
{t:'Escrever na mesma base',c:'Como $8=2^3$, fica $2^x=2^3$.'},
{t:'Igualar os expoentes',c:'A exponencial é injetiva, logo $x=3$. Solução: $\\{3\\}$.'}]},
erros:[
{e:'Escrever $\\log(a+b)=\\log a+\\log b$.',c:'A propriedade é para o produto: $\\log(ab)=\\log a+\\log b$.'},
{e:'Esquecer o domínio ao resolver equações com logaritmos.',c:'No fim, verifica que o argumento de cada logaritmo é positivo.'},
{e:'Achar que $a^x$ pode ser zero ou negativo.',c:'$a^x>0$ para todo o $x$ — equações como $2^x=-4$ são impossíveis.'}]},
{id:'trig',titulo:'Trigonometria',icone:'triangle',dif:'Difícil',duracao:'60 min',grad:'linear-gradient(135deg,#fb7185,#e11d48)',
desc:'Círculo trigonométrico, valores notáveis, fórmula fundamental e equações trigonométricas.',
video:{id:'OPsqOAgxR4g',titulo:"Círculo trigonométrico — seno e cosseno",canal:"Sandro Curió"},
dicaFacil:"No círculo: cosseno é o x, seno é o y. Equações como sin x = k têm (quase sempre) duas soluções por volta — um em cada quadrante com o sinal certo. Trabalha em radianos.",

teoria:[
'No círculo trigonométrico (raio 1), o cosseno é a abcissa e o seno é a ordenada do ponto associado ao ângulo. Os sinais dependem do quadrante: no 1.º ambos positivos, no 2.º só o seno, no 3.º nenhum, no 4.º só o cosseno.',
'Os valores notáveis ($\\frac{\\pi}{6}$, $\\frac{\\pi}{4}$, $\\frac{\\pi}{3}$) devem estar memorizados. A fórmula fundamental $\\sin^2 x+\\cos^2 x=1$ permite calcular uma razão a partir da outra, escolhendo o sinal pelo quadrante.',
'Uma equação como $\\sin x = k$ tem, em geral, duas famílias de soluções: se $\\sin x=\\sin\\alpha$, então $x=\\alpha+2k\\pi$ ou $x=\\pi-\\alpha+2k\\pi$. Para o cosseno: $x=\\pm\\alpha+2k\\pi$. As funções $\\sin$ e $\\cos$ têm período $2\\pi$; a função $\\sin(bx)$ tem período $\\frac{2\\pi}{|b|}$.'],
formulas:[
{n:'Fórmula fundamental',t:'$$\\sin^2 x+\\cos^2 x=1$$'},
{n:'Tangente',t:'$$\\tan x=\\frac{\\sin x}{\\cos x}$$'},
{n:'Consequência da fundamental',t:'$$1+\\tan^2 x=\\frac{1}{\\cos^2 x}$$'},
{n:'Valores notáveis do seno',t:'$$\\sin\\tfrac{\\pi}{6}=\\tfrac12,\\quad \\sin\\tfrac{\\pi}{4}=\\tfrac{\\sqrt2}{2},\\quad \\sin\\tfrac{\\pi}{3}=\\tfrac{\\sqrt3}{2}$$'},
{n:'Período de sin(bx)',t:'$$T=\\frac{2\\pi}{|b|}$$'}],
exemplo:{e:'Resolva a equação $\\sin x = \\tfrac12$ no intervalo $[0, 2\\pi]$.',passos:[
{t:'Encontrar a solução de referência',c:'O valor notável dá $\\alpha=\\frac{\\pi}{6}$, pois $\\sin\\frac{\\pi}{6}=\\frac12$.'},
{t:'Encontrar a segunda solução',c:'O seno é positivo também no 2.º quadrante: $x=\\pi-\\frac{\\pi}{6}=\\frac{5\\pi}{6}$.'},
{t:'Apresentar o conjunto-solução',c:'Em $[0,2\\pi]$: $S=\\left\\{\\frac{\\pi}{6},\\ \\frac{5\\pi}{6}\\right\\}$.'}]},
erros:[
{e:'Dar apenas uma solução da equação trigonométrica.',c:'Verifica sempre os dois quadrantes onde a razão tem o sinal pedido.'},
{e:'Misturar graus com radianos.',c:'Trabalha sempre em radianos: $180°=\\pi$.'},
{e:'Errar o sinal de $\\cos x$ ao usar a fórmula fundamental.',c:'O quadrante indicado no enunciado decide o sinal da raiz.'}]},
{id:'lim',titulo:'Limites e continuidade',icone:'infinity',dif:'Difícil',duracao:'55 min',grad:'linear-gradient(135deg,#22d3ee,#0e7490)',
desc:'Limites laterais, continuidade num ponto, funções definidas por ramos e indeterminações 0/0.',
video:{id:'wPesFG0cG7g',titulo:"Domínio de uma função real (base para limites)",canal:"Sandro Curió"},
dicaFacil:"O limite existe se esquerda e direita dão o mesmo. Em funções por ramos, usa cada ramo no seu lado. Se der 0/0, fatoriza e cancela antes de substituir. Continuidade = limite = valor da função.",

teoria:[
'O limite de $f$ quando $x\\to a$ existe quando os limites laterais (à esquerda e à direita) existem e são iguais. Nas funções definidas por ramos, cada limite lateral calcula-se com o ramo correspondente.',
'Uma função é contínua em $a$ quando três condições se cumprem: $f(a)$ existe, $\\lim_{x\\to a}f(x)$ existe e $\\lim_{x\\to a}f(x)=f(a)$. É este o critério a usar nos exercícios de «determinar $k$ para que $f$ seja contínua».',
'Numa indeterminação $\\frac{0}{0}$ com polinómios, fatoriza-se o numerador e o denominador e simplifica-se o fator comum $(x-a)$. Nos limites em $\\pm\\infty$ de quocientes de polinómios, mandam os termos de maior grau.'],
formulas:[
{n:'Continuidade em a',t:'$$\\lim_{x\\to a^-}f(x)=\\lim_{x\\to a^+}f(x)=f(a)$$'},
{n:'Polinómios no infinito',t:'$$\\lim_{x\\to\\pm\\infty}P(x)=\\lim_{x\\to\\pm\\infty}a_nx^n$$'},
{n:'Levantar 0/0 por fatorização',t:'$$\\lim_{x\\to a}\\frac{(x-a)\\,g(x)}{(x-a)\\,h(x)}=\\lim_{x\\to a}\\frac{g(x)}{h(x)}$$'},
{n:'Caso notável',t:'$$\\lim_{x\\to a}\\frac{x^2-a^2}{x-a}=2a$$'}],
exemplo:{e:'Determine $k$ de modo que a função $f(x)=\\begin{cases}x^2-1 & \\text{se } x<2\\\\ 3x+k & \\text{se } x\\geq 2\\end{cases}$ seja contínua em $x=2$.',passos:[
{t:'Limite à esquerda',c:'Usa-se o ramo $x^2-1$: $\\lim_{x\\to 2^-}f(x)=4-1=3$.'},
{t:'Limite à direita e valor da função',c:'Usa-se o ramo $3x+k$: $\\lim_{x\\to 2^+}f(x)=f(2)=6+k$.'},
{t:'Impor a continuidade',c:'Para $f$ ser contínua: $6+k=3 \\Rightarrow k=-3$.'}]},
erros:[
{e:'Calcular só um limite lateral em funções por ramos.',c:'Perto do ponto de mudança de ramo, os dois lados são obrigatórios.'},
{e:'Concluir continuidade só porque $f(a)$ existe.',c:'É preciso que o limite exista e seja igual a $f(a)$ — três condições.'},
{e:'Substituir diretamente numa indeterminação $\\frac00$.',c:'Primeiro fatoriza e simplifica; só depois substitui.'}]},
{id:'der',titulo:'Derivadas',icone:'activity',dif:'Difícil',duracao:'65 min',grad:'linear-gradient(135deg,#60a5fa,#1d4ed8)',
desc:'Regras de derivação, reta tangente, monotonia e extremos relativos.',
video:{id:'bZm6KZ_Cy2o',titulo:"Equação reduzida da reta — declive (ideia de derivada)",canal:"Sandro Curió"},
dicaFacil:"A derivada é o declive da tangente (taxa de variação). Regras: (x^n)'=n x^(n−1). Para monotonia: f'>0 crescente, f'<0 decrescente. Extremo só quando f' anula e muda de sinal.",

teoria:[
'A derivada $f\'(a)$ é o declive da reta tangente ao gráfico de $f$ no ponto de abcissa $a$ — mede a taxa de variação instantânea. A equação da tangente é $y=f(a)+f\'(a)(x-a)$.',
'As regras práticas evitam a definição: a derivada da potência é $(x^n)\'=nx^{n-1}$, a derivada da soma é a soma das derivadas e as constantes multiplicativas saem para fora. Para produtos e quocientes há regras próprias.',
'O sinal de $f\'$ dá a monotonia: $f\'>0$ → crescente, $f\'<0$ → decrescente. Um extremo relativo ocorre onde $f\'$ se anula e muda de sinal — anular-se não chega (ex.: $f(x)=x^3$ em $x=0$). O quadro de sinais de $f\'$ organiza o estudo.'],
formulas:[
{n:'Definição',t:'$$f\'(a)=\\lim_{h\\to 0}\\frac{f(a+h)-f(a)}{h}$$'},
{n:'Potência',t:'$$(x^n)\'=n\\,x^{n-1}$$'},
{n:'Produto',t:'$$(u\\,v)\'=u\'v+u\\,v\'$$'},
{n:'Quociente',t:'$$\\left(\\frac{u}{v}\\right)\'=\\frac{u\'v-u\\,v\'}{v^2}$$'},
{n:'Reta tangente em a',t:'$$y=f(a)+f\'(a)\\,(x-a)$$'}],
exemplo:{e:'Estude a monotonia e os extremos de $f(x)=x^3-3x^2$.',passos:[
{t:'Derivar',c:'$f\'(x)=3x^2-6x=3x(x-2)$.'},
{t:'Zeros da derivada',c:'$f\'(x)=0 \\iff x=0 \\lor x=2$.'},
{t:'Quadro de sinais',c:'$f\'>0$ em $]-\\infty,0[$ e $]2,+\\infty[$ (crescente); $f\'<0$ em $]0,2[$ (decrescente).'},
{t:'Concluir os extremos',c:'Máximo relativo $f(0)=0$ em $x=0$; mínimo relativo $f(2)=8-12\\cdot 1=-4$ em $x=2$.'}]},
erros:[
{e:'Confundir $f\'(a)$ (declive) com $f(a)$ (ordenada).',c:'A tangente precisa dos dois: passa em $(a,f(a))$ com declive $f\'(a)$.'},
{e:'Concluir extremo só porque $f\'(a)=0$.',c:'A derivada tem de mudar de sinal em $a$.'},
{e:'Errar a regra do quociente trocando a ordem do numerador.',c:'É $u\'v-uv\'$ — a ordem importa por causa do sinal.'}]},
{id:'pg',titulo:'Progressões geométricas',icone:'list-ordered',dif:'Fácil',duracao:'40 min',grad:'linear-gradient(135deg,#a3e635,#4d7c0f)',
desc:'Termo geral, razão, soma de n termos e soma da série geométrica.',
video:{id:'haKrC4quHj8',titulo:"Progressão geométrica — termo geral e soma",canal:"Sandro Curió"},
dicaFacil:"Em PG cada termo multiplica pela razão r. Termo geral: u_n = u_1 · r^(n−1). Soma de n termos: S_n = u_1(1−r^n)/(1−r). Série infinita só se |r|<1: S = u_1/(1−r).",

teoria:[
'Numa progressão geométrica cada termo obtém-se do anterior multiplicando por uma constante $r$ (a razão): $u_{n+1}=u_n\\cdot r$. O termo geral é $u_n=u_1\\cdot r^{\\,n-1}$.',
'A monotonia depende de $u_1$ e $r$: com $u_1>0$, a sucessão é crescente se $r>1$ e decrescente se $0<r<1$; com $r<0$ os termos alternam de sinal e não há monotonia.',
'A soma dos $n$ primeiros termos é $S_n=u_1\\cdot\\frac{1-r^n}{1-r}$ (com $r\\neq 1$). Quando $|r|<1$, $r^n\\to 0$ e a série geométrica converge: a soma de todos os termos é $S=\\frac{u_1}{1-r}$.'],
formulas:[
{n:'Termo geral',t:'$$u_n=u_1\\cdot r^{\\,n-1}$$'},
{n:'Razão',t:'$$r=\\frac{u_{n+1}}{u_n}$$'},
{n:'Soma de n termos',t:'$$S_n=u_1\\cdot\\frac{1-r^n}{1-r}\\quad (r\\neq 1)$$'},
{n:'Soma da série (|r|<1)',t:'$$S=\\frac{u_1}{1-r}$$'}],
exemplo:{e:'Numa progressão geométrica de termos positivos, $u_3=12$ e $u_5=48$. Determine a razão, o primeiro termo e $S_6$.',passos:[
{t:'Encontrar a razão',c:'$\\frac{u_5}{u_3}=r^2=\\frac{48}{12}=4$; como os termos são positivos, $r=2$.'},
{t:'Encontrar o primeiro termo',c:'$u_3=u_1\\cdot r^2 \\Rightarrow 12=u_1\\cdot 4 \\Rightarrow u_1=3$.'},
{t:'Calcular a soma',c:'$S_6=3\\cdot\\frac{1-2^6}{1-2}=3\\cdot\\frac{-63}{-1}=189$.'}]},
erros:[
{e:'Confundir com progressão aritmética (somar em vez de multiplicar).',c:'Na PG a razão é um quociente: $r=\\frac{u_{n+1}}{u_n}$.'},
{e:'Escrever $u_n=u_1\\cdot r^n$.',c:'O expoente é $n-1$: no termo 1 ainda não se multiplicou nada.'},
{e:'Usar a soma da série infinita com $|r|\\geq 1$.',c:'A série só converge quando $|r|<1$.'}]}
];

export const QUESTOES = [
{"id":"c1","tema":"comb","dif":"Fácil","q":"Com os algarismos $1, 2, 3, 4$ e $5$, quantos números de três algarismos diferentes se podem formar?","ops":["60","125","10","120"],"c":0,"passos":["A ordem importa e não há repetição: são arranjos.","$^5A_3=5\\times 4\\times 3=60$ números."],"fonte":"Banco MatPrep"},
{"id":"c2","tema":"comb","dif":"Médio","q":"Numa turma de 8 alunos, quantos grupos de 3 alunos diferentes se podem formar?","ops":["56","336","24","512"],"c":0,"passos":["A ordem não importa (um grupo é um conjunto): combinações.","$^8C_3=\\frac{8!}{3!\\,5!}=\\frac{8\\times 7\\times 6}{6}=56$ grupos."],"fonte":"Banco MatPrep"},
{"id":"c3","tema":"comb","dif":"Médio","q":"Numa linha do Triângulo de Pascal, a soma de todos os elementos é $1024$. Quantos elementos tem essa linha?","ops":["11","10","1024","12"],"c":0,"passos":["A soma da linha $n$ é $2^n$: $2^n=1024\\Rightarrow n=10$.","A linha $n=10$ tem $n+1=11$ elementos."],"fonte":"Banco MatPrep"},
{"id":"c4","tema":"comb","dif":"Difícil","q":"De quantas maneiras se podem sentar numa fila 4 raparigas e 3 rapazes, ficando os 3 rapazes juntos?","ops":["720","5040","144","240"],"c":0,"passos":["Juntam-se os rapazes num bloco: ficam 5 elementos a permutar — $5!=120$.","Dentro do bloco, os rapazes trocam entre si: $3!=6$.","Total: $120\\times 6=720$ maneiras."],"fonte":"Banco MatPrep"},
{"id":"p1","tema":"prob","dif":"Fácil","q":"Sabe-se que $P(A)=0{,}5$ e $P(B)=0{,}3$, sendo $A$ e $B$ incompatíveis. Qual é o valor de $P(A\\cup B)$?","ops":["0,8","0,15","0,2","0,5"],"c":0,"passos":["Incompatíveis significa $P(A\\cap B)=0$.","$P(A\\cup B)=0{,}5+0{,}3=0{,}8$."],"fonte":"Banco MatPrep"},
{"id":"p2","tema":"prob","dif":"Médio","q":"Sabe-se que $P(A)=0{,}6$, $P(B)=0{,}5$ e $P(A\\cap B)=0{,}3$. Qual é o valor de $P(A\\cup B)$?","ops":["0,8","1,1","0,9","0,3"],"c":0,"passos":["Aplica-se $P(A\\cup B)=P(A)+P(B)-P(A\\cap B)$.","$0{,}6+0{,}5-0{,}3=0{,}8$."],"fonte":"Banco MatPrep"},
{"id":"p3","tema":"prob","dif":"Médio","q":"Sabe-se que $P(A\\cap B)=0{,}2$ e $P(B)=0{,}4$. Qual é o valor de $P(A\\mid B)$?","ops":["0,5","0,08","0,2","0,6"],"c":0,"passos":["Aplica-se a definição: $P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}$.","$P(A\\mid B)=\\frac{0{,}2}{0{,}4}=0{,}5$."],"fonte":"Banco MatPrep"},
{"id":"p4","tema":"prob","dif":"Difícil","q":"Um saco tem 3 bolas vermelhas e 2 azuis. Extraem-se 2 bolas, sem reposição. Qual é a probabilidade de ambas serem vermelhas?","ops":["$\\tfrac{3}{10}$","$\\tfrac{9}{25}$","$\\tfrac{2}{5}$","$\\tfrac{3}{5}$"],"c":0,"passos":["1.ª extração: $P=\\frac{3}{5}$.","2.ª extração (sem reposição, sabendo que a 1.ª foi vermelha): $P=\\frac{2}{4}$.","$P=\\frac{3}{5}\\times\\frac{2}{4}=\\frac{6}{20}=\\frac{3}{10}$."],"fonte":"Banco MatPrep"},
{"id":"f1","tema":"func","dif":"Fácil","q":"Qual é o declive da reta que passa pelos pontos $(1,2)$ e $(3,8)$?","ops":["3","2","6","$\\tfrac13$"],"c":0,"passos":["$m=\\frac{y_2-y_1}{x_2-x_1}=\\frac{8-2}{3-1}$.","$m=\\frac{6}{2}=3$."],"fonte":"Banco MatPrep"},
{"id":"f2","tema":"func","dif":"Médio","q":"Quais são as coordenadas do vértice da parábola $f(x)=x^2-4x+1$?","ops":["$(2,-3)$","$(-2,13)$","$(2,3)$","$(4,1)$"],"c":0,"passos":["$x_v=-\\frac{b}{2a}=-\\frac{-4}{2}=2$.","$y_v=f(2)=4-8+1=-3$. Vértice: $(2,-3)$."],"fonte":"Banco MatPrep"},
{"id":"f3","tema":"func","dif":"Médio","q":"Quais são os zeros da função $f(x)=x^2-5x+6$?","ops":["$2$ e $3$","$-2$ e $-3$","$1$ e $6$","$-1$ e $6$"],"c":0,"passos":["Fórmula resolvente: $x=\\frac{5\\pm\\sqrt{25-24}}{2}=\\frac{5\\pm 1}{2}$.","$x=2$ ou $x=3$."],"fonte":"Banco MatPrep"},
{"id":"f4","tema":"func","dif":"Difícil","q":"Qual é o contradomínio da função $f(x)=-2(x-1)^2+8$?","ops":["$\\left]-\\infty,8\\right]$","$\\left[8,+\\infty\\right[$","$\\left[1,+\\infty\\right[$","$\\left]-\\infty,1\\right]$"],"c":0,"passos":["A forma canónica mostra o vértice $(1,8)$.","Como $a=-2<0$, a concavidade está para baixo: $8$ é máximo.","$D'_f=\\left]-\\infty,8\\right]$."],"fonte":"Banco MatPrep"},
{"id":"e1","tema":"explog","dif":"Fácil","q":"Qual é o valor de $\\log_2 32$?","ops":["5","16","4","6"],"c":0,"passos":["Procura-se $y$ tal que $2^y=32$.","$32=2^5$, logo $\\log_2 32=5$."],"fonte":"Banco MatPrep"},
{"id":"e2","tema":"explog","dif":"Médio","q":"Qual é a solução da equação $2^{x+1}=16$?","ops":["3","4","8","15"],"c":0,"passos":["$16=2^4$, logo $2^{x+1}=2^4$.","Igualando expoentes: $x+1=4\\Rightarrow x=3$."],"fonte":"Banco MatPrep"},
{"id":"e3","tema":"explog","dif":"Médio","q":"Qual é a solução da equação $\\ln x = 2$?","ops":["$e^2$","$2e$","$\\ln 2$","$\\sqrt{e}$"],"c":0,"passos":["Pela definição de logaritmo: $x=e^2$.","Como $e^2>0$, a solução pertence ao domínio."],"fonte":"Banco MatPrep"},
{"id":"e4","tema":"explog","dif":"Difícil","q":"Qual é a solução da equação $\\log_2(x-1)=3$?","ops":["9","7","8","4"],"c":0,"passos":["Pela definição: $x-1=2^3=8$.","$x=9$; verificação: $x-1=8>0$ ✓."],"fonte":"Banco MatPrep"},
{"id":"t1","tema":"trig","dif":"Fácil","q":"Qual é o valor de $\\sin\\frac{\\pi}{6}$?","ops":["$\\tfrac12$","$\\tfrac{\\sqrt2}{2}$","$\\tfrac{\\sqrt3}{2}$","$1$"],"c":0,"passos":["$\\frac{\\pi}{6}$ corresponde a $30°$.","Valor notável: $\\sin\\frac{\\pi}{6}=\\frac12$."],"fonte":"Banco MatPrep"},
{"id":"t2","tema":"trig","dif":"Médio","q":"Sabendo que $\\cos x=-\\tfrac12$ e $x\\in[0,\\pi]$, qual é o valor de $x$?","ops":["$\\tfrac{2\\pi}{3}$","$\\tfrac{\\pi}{3}$","$\\tfrac{5\\pi}{6}$","$\\tfrac{\\pi}{6}$"],"c":0,"passos":["O cosseno é negativo no 2.º quadrante e $\\cos\\frac{\\pi}{3}=\\frac12$.","$x=\\pi-\\frac{\\pi}{3}=\\frac{2\\pi}{3}$."],"fonte":"Banco MatPrep"},
{"id":"t3","tema":"trig","dif":"Médio","q":"Sabendo que $\\sin x=\\tfrac35$ e que $x$ pertence ao 1.º quadrante, qual é o valor de $\\cos x$?","ops":["$\\tfrac45$","$\\tfrac34$","$-\\tfrac45$","$\\tfrac{16}{25}$"],"c":0,"passos":["Fórmula fundamental: $\\cos^2 x=1-\\frac{9}{25}=\\frac{16}{25}$.","No 1.º quadrante o cosseno é positivo: $\\cos x=\\frac45$."],"fonte":"Banco MatPrep"},
{"id":"t4","tema":"trig","dif":"Difícil","q":"Qual é o período da função $f(x)=3\\sin(2x)+1$?","ops":["$\\pi$","$2\\pi$","$\\tfrac{\\pi}{2}$","$4\\pi$"],"c":0,"passos":["O período de $\\sin(bx)$ é $\\frac{2\\pi}{|b|}$.","Com $b=2$: $T=\\frac{2\\pi}{2}=\\pi$ (a amplitude e o $+1$ não alteram o período)."],"fonte":"Banco MatPrep"},
{"id":"l1","tema":"lim","dif":"Fácil","q":"Qual é o valor de $\\displaystyle\\lim_{x\\to 2}\\frac{x^2-4}{x-2}$?","ops":["4","0","2","não existe"],"c":0,"passos":["Substituição direta dá $\\frac00$: fatoriza-se $x^2-4=(x-2)(x+2)$.","Simplificando: $\\lim_{x\\to 2}(x+2)=4$."],"fonte":"Banco MatPrep"},
{"id":"l2","tema":"lim","dif":"Médio","q":"Qual é o valor de $\\displaystyle\\lim_{x\\to+\\infty}\\frac{3x^2+1}{x^2-5}$?","ops":["3","$+\\infty$","0","1"],"c":0,"passos":["No infinito mandam os termos de maior grau.","$\\lim_{x\\to+\\infty}\\frac{3x^2}{x^2}=3$."],"fonte":"Banco MatPrep"},
{"id":"l3","tema":"lim","dif":"Médio","q":"Considere $f(x)=\\begin{cases}x^2+k & \\text{se } x\\leq 1\\\\ 2x+1 & \\text{se } x>1\\end{cases}$. Para que valor de $k$ é $f$ contínua em $x=1$?","ops":["2","0","3","$-2$"],"c":0,"passos":["Limite à esquerda (e valor): $1+k$; limite à direita: $2+1=3$.","Continuidade: $1+k=3\\Rightarrow k=2$."],"fonte":"Banco MatPrep"},
{"id":"l4","tema":"lim","dif":"Difícil","q":"Qual é o valor de $\\displaystyle\\lim_{x\\to 1^-}\\frac{1}{x-1}$?","ops":["$-\\infty$","$+\\infty$","0","1"],"c":0,"passos":["À esquerda de 1, $x-1$ é negativo e tende para $0^-$.","$\\frac{1}{0^-}=-\\infty$."],"fonte":"Banco MatPrep"},
{"id":"d1","tema":"der","dif":"Fácil","q":"Sendo $f(x)=x^3$, qual é o valor de $f'(2)$?","ops":["12","8","6","3"],"c":0,"passos":["Regra da potência: $f'(x)=3x^2$.","$f'(2)=3\\times 4=12$."],"fonte":"Banco MatPrep"},
{"id":"d2","tema":"der","dif":"Médio","q":"Qual é a equação da reta tangente ao gráfico de $f(x)=x^2$ no ponto de abcissa $x=1$?","ops":["$y=2x-1$","$y=2x+1$","$y=x-1$","$y=2x$"],"c":0,"passos":["Declive: $f'(x)=2x$, logo $m=f'(1)=2$.","Ponto de tangência: $(1,1)$. Reta: $y-1=2(x-1)\\iff y=2x-1$."],"fonte":"Banco MatPrep"},
{"id":"d3","tema":"der","dif":"Médio","q":"A função $f(x)=x^3-3x$ tem um mínimo relativo em:","ops":["$x=1$","$x=-1$","$x=0$","$x=3$"],"c":0,"passos":["$f'(x)=3x^2-3=3(x-1)(x+1)$; zeros em $x=\\pm 1$.","O quadro de sinais mostra $f'$ a passar de negativa a positiva em $x=1$: mínimo relativo."],"fonte":"Banco MatPrep"},
{"id":"d4","tema":"der","dif":"Difícil","q":"Sendo $f(x)=\\dfrac{2x+1}{x-1}$, qual é o valor de $f'(0)$?","ops":["$-3$","3","$-1$","1"],"c":0,"passos":["Regra do quociente: $f'(x)=\\frac{2(x-1)-(2x+1)\\cdot 1}{(x-1)^2}=\\frac{-3}{(x-1)^2}$.","$f'(0)=\\frac{-3}{1}=-3$."],"fonte":"Banco MatPrep"},
{"id":"g1","tema":"pg","dif":"Fácil","q":"Numa progressão geométrica com $u_1=2$ e razão $r=3$, qual é o valor de $u_4$?","ops":["54","18","162","24"],"c":0,"passos":["Termo geral: $u_n=u_1\\cdot r^{\\,n-1}$.","$u_4=2\\times 3^3=2\\times 27=54$."],"fonte":"Banco MatPrep"},
{"id":"g2","tema":"pg","dif":"Médio","q":"Qual é a soma dos 5 primeiros termos da progressão geométrica com $u_1=1$ e $r=2$?","ops":["31","32","16","63"],"c":0,"passos":["$S_5=1\\cdot\\frac{1-2^5}{1-2}$.","$S_5=\\frac{1-32}{-1}=31$."],"fonte":"Banco MatPrep"},
{"id":"g3","tema":"pg","dif":"Médio","q":"Numa progressão geométrica tem-se $u_2=6$ e $u_4=24$, com $r>0$. Qual é a razão?","ops":["2","4","3","$\\sqrt2$"],"c":0,"passos":["$\\frac{u_4}{u_2}=r^2=\\frac{24}{6}=4$.","Como $r>0$: $r=2$."],"fonte":"Banco MatPrep"},
{"id":"g4","tema":"pg","dif":"Difícil","q":"Qual é a soma da série geométrica $4+2+1+\\tfrac12+\\dots$?","ops":["8","7","6","$+\\infty$"],"c":0,"passos":["Razão: $r=\\frac24=\\frac12$; como $|r|<1$, a série converge.","$S=\\frac{u_1}{1-r}=\\frac{4}{1-\\frac12}=8$."],"fonte":"Banco MatPrep"},
{"id":"r1","tema":"comb","dif":"Médio","q":"No Triângulo de Pascal, a soma de quatro elementos consecutivos menores é $12$. Qual é o terceiro elemento seguinte?","ops":["15","12","13","16"],"c":0,"passos":["Os quatro elementos são $1,3,3,5$, cuja soma é $12$.","Pela regra de Pascal, os elementos seguintes obtêm-se somando os dois anteriores: $6,8,13,15$."],"fonte":"Prova modelo 1"},
{"id":"r2","tema":"comb","dif":"Médio","q":"O segundo elemento de uma linha do Triângulo de Pascal é $15$. Qual é o terceiro elemento da linha anterior?","ops":["105","91","120","15"],"c":1,"passos":["O segundo elemento da linha $n$ é $n$; logo trata-se da linha $15$.","Na linha anterior, o terceiro elemento é $^{14}C_2=\\frac{14\\times13}{2}=91$."],"fonte":"Exame 2024 Recurso"},
{"id":"r3","tema":"comb","dif":"Fácil","q":"Numa linha do Triângulo de Pascal, o primeiro elemento diferente de $1$ é $29$. Qual é o terceiro elemento dessa linha?","ops":["$^{28}C_2=378$","29","$^{29}C_2=406$","$2^{29}$"],"c":2,"passos":["O primeiro elemento diferente de $1$ na linha $n$ é $n$; a linha é a 29.","O terceiro elemento é $^{29}C_2=\\frac{29\\times28}{2}=406$."],"fonte":"Exame 2023"},
{"id":"r4","tema":"comb","dif":"Médio","q":"No desenvolvimento de $(x+2)^8$, qual é o coeficiente de $x^5$?","ops":["224","56","896","448"],"c":3,"passos":["Para obter $x^5$, escolhe-se $x^5$ e três vezes o termo $2$.","O coeficiente é $^8C_3\\cdot2^3=56\\cdot8=448$."],"fonte":"Prova modelo 1"},
{"id":"r5","tema":"comb","dif":"Médio","q":"No desenvolvimento de $(x-1)^8$, qual é o coeficiente de $x^6$?","ops":["28","$-28$","56","8"],"c":0,"passos":["O termo em $x^6$ usa duas vezes $(-1)$.","$^8C_2(-1)^2=28$."],"fonte":"Exame 2024 Normal"},
{"id":"r6","tema":"comb","dif":"Fácil","q":"No desenvolvimento de $(x+3)^7$, qual é o coeficiente de $x^6$?","ops":["7","21","63","$-21$"],"c":1,"passos":["Para o grau 6 escolhe-se uma vez o termo $3$.","$^7C_1\\cdot3=7\\cdot3=21$."],"fonte":"Exame 2022"},
{"id":"r7","tema":"comb","dif":"Médio","q":"O terceiro termo de $(x+2)^n$ é $24x^{n-2}$. Determine $n$.","ops":["3","5","4","6"],"c":2,"passos":["O terceiro termo é $^nC_2x^{n-2}2^2$.","Logo $4\\cdot\\frac{n(n-1)}2=24$, isto é, $n(n-1)=12$; $n=4$."],"fonte":"Exame 2023"},
{"id":"r8","tema":"comb","dif":"Difícil","q":"Um volante do Totoloto exige 5 números de 49 e 1 estrela de 13. Quantas apostas simples diferentes existem?","ops":["$49^5\\cdot13$","$^{49}A_5\\cdot13$","$^{62}C_6$","$^{49}C_5\\cdot{}^{13}C_1$"],"c":3,"passos":["A ordem dos cinco números não cria uma nova aposta: há $^{49}C_5$ escolhas.","A estrela é escolhida independentemente: $^{13}C_1$; aplica-se o princípio multiplicativo."],"fonte":"Ficha Combinatória"},
{"id":"r9","tema":"comb","dif":"Difícil","q":"De quantas maneiras se formam comissões de 4 alunos de uma turma de 10, sabendo que Ana e Bruno não podem pertencer ambos à comissão?","ops":["$^{10}C_4-{}^8C_2=182$","$^{10}C_4=210$","$^8C_2=28$","$^{10}A_4$"],"c":0,"passos":["Há $^{10}C_4=210$ comissões sem restrição.","As proibidas contêm Ana e Bruno e mais 2 dos 8 restantes: $^8C_2=28$. Logo $210-28=182$."],"fonte":"Ficha Combinatória"},
{"id":"r10","tema":"comb","dif":"Médio","q":"Quantas palavras de 5 letras distintas se podem formar com as letras de MATEMATICA, usando apenas as letras diferentes?","ops":["$^6C_5=6$","$^6A_5=720$","$6^5$","$5!$"],"c":1,"passos":["As letras diferentes são M, A, T, E, I e C: seis letras.","A ordem importa e não há repetição: $^6A_5=6\\cdot5\\cdot4\\cdot3\\cdot2=720$."],"fonte":"Ficha Combinatória"},
{"id":"r11","tema":"prob","dif":"Médio","q":"Sabendo que $P(A)=0{,}6$, $P(B)=0{,}7$ e $P(A\\cap B)=0{,}5$, determine $P(B\\mid A)$.","ops":["$\\frac57$","$\\frac12$","$\\frac56$","0,5"],"c":2,"passos":["Usa-se $P(B\\mid A)=\\frac{P(A\\cap B)}{P(A)}$.","$\\frac{0,5}{0,6}=\\frac56$."],"fonte":"Exame 2024 Normal"},
{"id":"r12","tema":"prob","dif":"Médio","q":"Se $P(A)=0{,}5$, $P(B)=0{,}6$ e $P(A\\cup B)=0{,}8$, qual é $P(A\\cap B)$?","ops":["0,8","0,2","1,1","0,3"],"c":3,"passos":["Pela fórmula da união, $P(A\\cap B)=P(A)+P(B)-P(A\\cup B)$.","$0,5+0,6-0,8=0,3$."],"fonte":"Exame 2022"},
{"id":"r13","tema":"prob","dif":"Fácil","q":"Se $P(A\\mid B)=\\frac12$ e $P(B)=0{,}4$, qual é $P(A\\cap B)$?","ops":["0,2","0,5","0,8","0,1"],"c":0,"passos":["Da definição, $P(A\\cap B)=P(A\\mid B)P(B)$.","$\\frac12\\cdot0,4=0,2$."],"fonte":"Exame 2022"},
{"id":"r14","tema":"prob","dif":"Médio","q":"Numa escola, 70% dos alunos bebem café, 40% bebem chá e 25% bebem ambos. Qual é a probabilidade de beber café ou chá?","ops":["110%","85%","45%","25%"],"c":1,"passos":["A união conta os que bebem ambos duas vezes, pelo que se subtrai a interseção.","$0,70+0,40-0,25=0,85$, isto é, 85%."],"fonte":"Ficha Probabilidades"},
{"id":"r15","tema":"prob","dif":"Médio","q":"Uma ficha é laranja com probabilidade $\\frac23$. Escolhem-se duas fichas com reposição. Qual é a probabilidade de ambas serem laranja?","ops":["$\\frac23$","$\\frac29$","$\\frac49$","$\\frac13$"],"c":2,"passos":["Com reposição, as duas extrações são independentes.","$\\frac23\\times\\frac23=\\frac49$."],"fonte":"Ficha Probabilidades"},
{"id":"r16","tema":"prob","dif":"Difícil","q":"Uma fábrica A produz 70% das peças e B 30%. As taxas de defeito são 4% e 7%, respetivamente. Qual é a probabilidade de uma peça escolhida ser defeituosa?","ops":["0,11","0,04","0,07","0,049"],"c":3,"passos":["Seja D o acontecimento «defeituosa». Usa-se a probabilidade total.","$P(D)=0,70\\cdot0,04+0,30\\cdot0,07=0,049$."],"fonte":"Ficha Probabilidades"},
{"id":"r17","tema":"prob","dif":"Difícil","q":"Nas condições anteriores, sabendo que a peça é defeituosa, qual é a probabilidade de vir de B?","ops":["$\\frac{3}{7}\\approx42,9\\%$","30%","7%","$\\frac{7}{10}$"],"c":0,"passos":["P(B\\mid D)=\\frac{P(B)P(D\\mid B)}{P(D)}$.","$\\frac{0,30\\cdot0,07}{0,049}=\\frac{0,021}{0,049}=\\frac37$."],"fonte":"Ficha Probabilidades"},
{"id":"r18","tema":"prob","dif":"Médio","q":"Num teste, 40% dos alunos faltaram (F). Entre os que faltaram, um terço teve nota negativa (N). Determine $P(N\\mid F)$.","ops":["0,4","$\\frac13$","$\\frac{2}{3}$","$\\frac{1}{15}$"],"c":1,"passos":["A frase «entre os que faltaram» já define o universo condicionado.","Assim, $P(N\\mid F)=\\frac13$."],"fonte":"Ficha Probabilidades"},
{"id":"r19","tema":"prob","dif":"Difícil","q":"Se $P(A)=0{,}8$ e $P(B\\mid A)=\\frac{7}{40}$, qual é $P(A\\cap B)$?","ops":["0,175","0,56","0,14","0,625"],"c":2,"passos":["$P(A\\cap B)=P(B\\mid A)P(A)$.","$\\frac{7}{40}\\cdot0,8=\\frac{7}{50}=0,14$."],"fonte":"Ficha Probabilidades"},
{"id":"r20","tema":"prob","dif":"Médio","q":"Dois acontecimentos A e B são independentes e $P(A)=0{,}8$. Qual é $P(A\\mid B)$, admitindo $P(B)>0$?","ops":["$P(B)$","0,64","0,2","0,8"],"c":3,"passos":["Na independência, saber B não altera a probabilidade de A.","Portanto $P(A\\mid B)=P(A)=0,8$."],"fonte":"Ficha Probabilidades"},
{"id":"r21","tema":"func","dif":"Médio","q":"Qual é o vértice de $f(x)=2x^2-12x+10$?","ops":["$(3,-8)$","$(3,8)$","$(6,10)$","$(-3,46)$"],"c":0,"passos":["$x_v=-\\frac{-12}{2\\cdot2}=3$.","$f(3)=18-36+10=-8$; portanto $V=(3,-8)$."],"fonte":"Prova modelo 1"},
{"id":"r22","tema":"func","dif":"Médio","q":"Qual é o contradomínio de $f(x)=-x^2+2x$?","ops":["$[1,+\\infty[$","$]-\\infty,1]$","$\\mathbb R$","$]-\\infty,0]$"],"c":1,"passos":["$f(x)=-(x-1)^2+1$, logo o valor máximo é 1.","A parábola abre para baixo; os valores são $]-\\infty,1]$."],"fonte":"Exame 2024 Normal"},
{"id":"r23","tema":"func","dif":"Médio","q":"Qual é o contradomínio de $f(x)=x^2+2x$?","ops":["$]-\\infty,-1]$","$[0,+\\infty[$","$[-1,+\\infty[$","$\\mathbb R$"],"c":2,"passos":["$f(x)=(x+1)^2-1$, logo o mínimo é $-1$.","Como abre para cima, o contradomínio é $[-1,+\\infty[$."],"fonte":"Exame 2024 Recurso"},
{"id":"r24","tema":"func","dif":"Fácil","q":"Determine a equação da reta que passa por $(-1,3)$ e $(1,-1)$.","ops":["$y=2x+1$","$y=-x+2$","$y=2x-1$","$y=-2x+1$"],"c":3,"passos":["O declive é $\\frac{-1-3}{1-(-1)}=-2$.","Em $y=-2x+b$, usando $(1,-1)$ obtém-se $b=1$."],"fonte":"Exame 2025 Recurso"},
{"id":"r25","tema":"func","dif":"Médio","q":"Uma cultura de bactérias é modelada por $N(t)=9000\\cdot2^t$. Qual é o número inicial de bactérias?","ops":["9000","2","18000","0"],"c":0,"passos":["O instante inicial é $t=0$.","$N(0)=9000\\cdot2^0=9000$."],"fonte":"Ficha Funções"},
{"id":"r26","tema":"func","dif":"Médio","q":"A altura de um foguete é $h(t)=-t^2+16t-39$. Em que instante atinge a altura máxima?","ops":["$t=16$","$t=8$","$t=4$","$t=39$"],"c":1,"passos":["A altura é uma parábola com $a=-1$; o máximo ocorre no vértice.","$t_v=-\\frac{16}{2(-1)}=8$."],"fonte":"Ficha Funções"},
{"id":"r27","tema":"func","dif":"Fácil","q":"Quais são os zeros de $x^2-8x+15$?","ops":["$-3$ e $-5$","1 e 15","3 e 5","4 e 4"],"c":2,"passos":["Procura-se um produto 15 e soma 8: $3$ e $5$.","$x^2-8x+15=(x-3)(x-5)$."],"fonte":"Ficha Funções"},
{"id":"r28","tema":"func","dif":"Difícil","q":"Determine o domínio de $f(x)=\\sqrt{x^2+x}$.","ops":["$[-1,0]$","$\\mathbb R$","$]0,+\\infty[$","$]-\\infty,-1]\\cup[0,+\\infty[$"],"c":3,"passos":["É necessário $x^2+x=x(x+1)\\geq0$.","O produto é não negativo para $x\\leq-1$ ou $x\\geq0$."],"fonte":"Ficha Funções"},
{"id":"r29","tema":"func","dif":"Médio","q":"A reta $y=mx-3$ passa pelo ponto $(2,5)$. Qual é o valor de $m$?","ops":["4","1","$-4$","8"],"c":0,"passos":["Substitui-se o ponto na equação: $5=2m-3$.","$2m=8$, logo $m=4$."],"fonte":"Ficha Funções"},
{"id":"r30","tema":"func","dif":"Difícil","q":"Para que valor de $k$ a parábola $x^2+kx+9$ tem uma única raiz real?","ops":["$k=6$ apenas","$k=\\pm6$","$k=0$","$k=\\pm3$"],"c":1,"passos":["Uma única raiz exige discriminante nulo.","$\\Delta=k^2-4\\cdot1\\cdot9=0\\Rightarrow k^2=36\\Rightarrow k=\\pm6$."],"fonte":"Ficha Funções"},
{"id":"r31","tema":"explog","dif":"Fácil","q":"Resolva $3^x+2=29$.","ops":["$x=2$","$x=9$","$x=3$","$x=27$"],"c":2,"passos":["Isola-se a potência: $3^x=27$.","Como $27=3^3$, conclui-se $x=3$."],"fonte":"Ficha Exponenciais"},
{"id":"r32","tema":"explog","dif":"Médio","q":"Resolva $9^x=\\frac1{243}$.","ops":["$-\\frac32$","$\\frac52$","$-5$","$x=-\\frac52$"],"c":3,"passos":["$9^x=3^{2x}$ e $\\frac1{243}=3^{-5}$.","Igualando expoentes: $2x=-5$, logo $x=-\\frac52$."],"fonte":"Ficha Exponenciais"},
{"id":"r33","tema":"explog","dif":"Médio","q":"Resolva $\\log_2(5x+1)=4$.","ops":["$x=3$","$x=\\frac{15}{4}$","$x=4$","$x=-3$"],"c":0,"passos":["Pela definição, $5x+1=2^4=16$.","$5x=15$, logo $x=3$; o argumento é positivo."],"fonte":"Ficha Exponenciais"},
{"id":"r34","tema":"explog","dif":"Médio","q":"Calcule $\\log_2(32)-\\log_{10}(100)$.","ops":["5","3","2","7"],"c":1,"passos":["$\\log_2(32)=5$ e $\\log_{10}(100)=2$.","A diferença é $5-2=3$."],"fonte":"Exame 2024 Normal"},
{"id":"r35","tema":"explog","dif":"Médio","q":"Calcule $2\\log_3\\sqrt3+\\log_{\\sqrt3}3$.","ops":["2","4","3","$\\frac32$"],"c":2,"passos":["$\\log_3\\sqrt3=\\frac12$ e $\\log_{\\sqrt3}3=2$.","Assim, $2\\cdot\\frac12+2=3$."],"fonte":"Exame 2025 Recurso"},
{"id":"r36","tema":"explog","dif":"Difícil","q":"Resolva $\\log_3(x-1)+\\log_3(x+1)=1$.","ops":["$x=-2$","$x=\\sqrt{10}$","$x=1$","$x=2$"],"c":3,"passos":["No domínio, $x>1$; junta-se: $\\log_3(x^2-1)=1$.","$x^2-1=3$, logo $x=\\pm2$; pelo domínio, $x=2$."],"fonte":"Ficha Exponenciais"},
{"id":"r37","tema":"explog","dif":"Médio","q":"Qual é o domínio de $f(x)=\\ln(4-2x)$?","ops":["$]-\\infty,2[$","$]2,+\\infty[$","$\\mathbb R$","$[2,+\\infty[$"],"c":0,"passos":["O argumento do logaritmo tem de ser positivo.","$4-2x>0\\Rightarrow x<2$."],"fonte":"Ficha Exponenciais"},
{"id":"r38","tema":"explog","dif":"Difícil","q":"Resolva $2^{x+1}=8^{x-2}$.","ops":["$x=4$","$x=\\frac74$","$x=\\frac72$","$x=-\\frac74$"],"c":1,"passos":["Escreve-se $8=2^3$: $2^{x+1}=2^{3x-6}$.","$x+1=3x-6\\Rightarrow2x=7\\Rightarrow x=\\frac74$."],"fonte":"Ficha Exponenciais"},
{"id":"r39","tema":"explog","dif":"Médio","q":"Se $\\log_a 16=4$, qual é a base positiva $a\\ne1$?","ops":["4","16","2","$\\frac12$"],"c":2,"passos":["A definição dá $a^4=16$.","A base positiva que satisfaz é $a=2$."],"fonte":"Ficha Exponenciais"},
{"id":"r40","tema":"trig","dif":"Médio","q":"Resolva $\\tan x=\\sqrt3$ em $\\mathbb R$.","ops":["$x=\\frac\\pi6+2k\\pi$","$x=\\pi+k\\pi$","$x=\\frac{2\\pi}3+2k\\pi$","$x=\\frac\\pi3+k\\pi$"],"c":3,"passos":["$\\tan\\frac\\pi3=\\sqrt3$.","A tangente tem período $\\pi$, portanto $x=\\frac\\pi3+k\\pi$."],"fonte":"Exame 2025 Recurso"},
{"id":"r41","tema":"trig","dif":"Fácil","q":"Se $\\alpha\\in]\\frac\\pi2,\\pi[$, qual é o sinal de $\\cos\\alpha\\sin\\alpha$?","ops":["negativo","positivo","nulo","indeterminado"],"c":0,"passos":["No segundo quadrante, $\\sin\\alpha>0$ e $\\cos\\alpha<0$.","O produto de sinais opostos é negativo."],"fonte":"Exame 2021"},
{"id":"r42","tema":"trig","dif":"Fácil","q":"Se $\\cos\\alpha=0{,}7$, quanto vale $\\cos(\\pi-\\alpha)$?","ops":["$0,7$","$-0,7$","0","1,7"],"c":1,"passos":["Usa-se $\\cos(\\pi-\\alpha)=-\\cos\\alpha$.","Logo o valor é $-0,7$."],"fonte":"Exame 2021"},
{"id":"r43","tema":"trig","dif":"Médio","q":"Resolva $2\\sin x+1=0$ em $[0,2\\pi]$.","ops":["$\\left\\{\\frac\\pi6,\\frac{5\\pi}6\\right\\}$","$\\left\\{\\frac{\\pi}{6}\\right\\}$","$\\left\\{\\frac{7\\pi}{6},\\frac{11\\pi}{6}\\right\\}$","$\\left\\{\\frac{3\\pi}{2}\\right\\}$"],"c":2,"passos":["$\\sin x=-\\frac12$.","No intervalo pedido, isso ocorre nos quadrantes III e IV: $\\frac{7\\pi}{6}$ e $\\frac{11\\pi}{6}$."],"fonte":"Ficha Trigonometria"},
{"id":"r44","tema":"trig","dif":"Médio","q":"Resolva $\\cos x=-\\frac12$ em $[0,2\\pi]$.","ops":["$\\left\\{\\frac\\pi3,\\frac{5\\pi}3\\right\\}$","$\\left\\{\\frac{2\\pi}{3}\\right\\}$","$\\left\\{\\frac{5\\pi}{6}\\right\\}$","$\\left\\{\\frac{2\\pi}{3},\\frac{4\\pi}{3}\\right\\}$"],"c":3,"passos":["O ângulo de referência é $\\frac\\pi3$.","O cosseno é negativo nos quadrantes II e III."],"fonte":"Ficha Trigonometria"},
{"id":"r45","tema":"trig","dif":"Difícil","q":"A equação $\\sin x+\\cos x=4$ tem quantas soluções reais?","ops":["nenhuma","uma","duas","infinitas"],"c":0,"passos":["Para todo o $x$, $|\\sin x+\\cos x|\\leq\\sqrt2$.","Como $4>\\sqrt2$, a igualdade é impossível."],"fonte":"Ficha Trigonometria"},
{"id":"r46","tema":"trig","dif":"Médio","q":"Qual é o contradomínio de $f(x)=\\sin(3x)+1$?","ops":["$[-1,1]$","$[0,2]$","$[-2,2]$","$]0,2[$"],"c":1,"passos":["$\\sin(3x)$ varia em $[-1,1]$.","Somar 1 desloca todos os valores para $[0,2]$."],"fonte":"Ficha Trigonometria"},
{"id":"r47","tema":"trig","dif":"Fácil","q":"A função $f(x)=\\sin(2x)$ é par, ímpar ou nenhuma das duas?","ops":["par","nem par nem ímpar","ímpar","periódica apenas"],"c":2,"passos":["$f(-x)=\\sin(-2x)=-\\sin(2x)$.","Logo $f(-x)=-f(x)$, que é a definição de função ímpar."],"fonte":"Ficha Trigonometria"},
{"id":"r48","tema":"trig","dif":"Médio","q":"Sabendo que $\\sin x=\\frac35$ e $x$ está no segundo quadrante, qual é $\\cos x$?","ops":["$\\frac45$","$\\frac34$","$-\\frac35$","$-\\frac45$"],"c":3,"passos":["$\\cos^2x=1-\\sin^2x=1-\\frac9{25}=\\frac{16}{25}$.","No segundo quadrante o cosseno é negativo: $\\cos x=-\\frac45$."],"fonte":"Ficha Trigonometria"},
{"id":"r49","tema":"trig","dif":"Difícil","q":"Qual é o período de $f(x)=\\cos(4x-\\pi)$?","ops":["$\\frac\\pi2$","$2\\pi$","$\\pi$","$4\\pi$"],"c":0,"passos":["Para $\\cos(bx+c)$, o período é $\\frac{2\\pi}{|b|}$.","Com $b=4$, obtém-se $T=\\frac{2\\pi}{4}=\\frac\\pi2$."],"fonte":"Ficha Trigonometria"},
{"id":"r50","tema":"lim","dif":"Médio","q":"Calcule $\\lim_{x\\to0}\\frac{\\sin(2x)}{\\sin(5x)}$.","ops":["$\\frac52$","$\\frac25$","1","0"],"c":1,"passos":["Escreve-se como $\\frac{\\sin(2x)}{2x}\\cdot\\frac{5x}{\\sin(5x)}\\cdot\\frac25$.","Os dois primeiros fatores tendem para 1, logo o limite é $\\frac25$."],"fonte":"Ficha Limites"},
{"id":"r51","tema":"lim","dif":"Médio","q":"Calcule $\\lim_{x\\to1}\\frac{x-1}{\\sqrt{x}-1}$.","ops":["1","$\\frac12$","2","0"],"c":2,"passos":["Racionaliza-se: $x-1=(\\sqrt x-1)(\\sqrt x+1)$.","Simplificando, o limite de $\\sqrt x+1$ em 1 é 2."],"fonte":"Ficha Limites"},
{"id":"r52","tema":"lim","dif":"Médio","q":"Calcule $\\lim_{x\\to+\\infty}\\frac{\\ln x}{x^2}$.","ops":["$+\\infty$","1","não existe","0"],"c":3,"passos":["Qualquer potência positiva de $x$ cresce mais depressa do que $\\ln x$.","Logo o quociente tende para 0."],"fonte":"Ficha Limites"},
{"id":"r53","tema":"lim","dif":"Médio","q":"Calcule $\\lim_{x\\to+\\infty}\\frac{e^{2x}}{x^2}$.","ops":["$+\\infty$","0","1","$-\\infty$"],"c":0,"passos":["A exponencial de base maior que 1 domina qualquer polinómio.","Por isso o quociente diverge para $+\\infty$."],"fonte":"Ficha Limites"},
{"id":"r54","tema":"lim","dif":"Fácil","q":"Calcule $\\lim_{x\\to-\\infty}(-2x+1)$.","ops":["$-\\infty$","$+\\infty$","1","0"],"c":1,"passos":["Quando $x\\to-\\infty$, o termo $-2x$ tende para $+\\infty$.","O termo constante não altera o comportamento."],"fonte":"Exame 2025 Recurso"},
{"id":"r55","tema":"lim","dif":"Difícil","q":"Calcule $\\lim_{x\\to0}\\frac{e^{-x}-1}{x}$.","ops":["1","0","$-1$","$+\\infty$"],"c":2,"passos":["É o limite notável $\\lim_{u\\to0}\\frac{e^u-1}{u}=1$ com $u=-x$.","Então $\\frac{e^{-x}-1}{x}=-\\frac{e^u-1}{u}\\to-1$."],"fonte":"Ficha Limites"},
{"id":"r56","tema":"lim","dif":"Médio","q":"Calcule $\\lim_{x\\to3}\\frac{x^2-5x+6}{x-3}$.","ops":["6","0","5","1"],"c":3,"passos":["Fatoriza-se $x^2-5x+6=(x-2)(x-3)$.","Após simplificar, fica $\\lim_{x\\to3}(x-2)=1$."],"fonte":"Ficha Limites"},
{"id":"r57","tema":"lim","dif":"Difícil","q":"Determine $k$ para que $f(x)=\\begin{cases}kx+1,&x<2\\\\x^2-1,&x\\ge2\\end{cases}$ seja contínua em 2.","ops":["$k=\\frac12$","$k=1$","$k=\\frac32$","$k=-\\frac12$"],"c":0,"passos":["O limite à direita e o valor são $2^2-1=3$.","À esquerda tende para $2k+1$; $2k+1=3\\Rightarrow k=\\frac12$."],"fonte":"Ficha Limites"},
{"id":"r58","tema":"lim","dif":"Médio","q":"Calcule $\\lim_{x\\to+\\infty}\\frac{5x^4-3x}{-10x^4+x^2}$.","ops":["$\\frac12$","$-\\frac12$","$-2$","0"],"c":1,"passos":["Os termos dominantes são $5x^4$ e $-10x^4$.","O limite é o quociente dos coeficientes: $\\frac5{-10}=-\\frac12$."],"fonte":"Ficha Limites"},
{"id":"r59","tema":"lim","dif":"Difícil","q":"Para que valor de $a$ existe $\\lim_{x\\to1}\\frac{x^2-a}{x-1}$ finito?","ops":["$a=0$","$a=2$","$a=1$","qualquer $a$"],"c":2,"passos":["Para evitar um numerador não nulo sobre algo que tende a zero, é preciso $1^2-a=0$.","Assim $a=1$; então a expressão simplifica-se para $x+1$."],"fonte":"Ficha Limites"},
{"id":"r60","tema":"der","dif":"Fácil","q":"Qual é a derivada de $3x+5$?","ops":["$3x$","5","0","3"],"c":3,"passos":["A derivada de $3x$ é 3 e a de uma constante é 0.","Logo $(3x+5)'=3$."],"fonte":"Ficha Derivadas"},
{"id":"r61","tema":"der","dif":"Médio","q":"Qual é a derivada de $x\\ln x$?","ops":["$\\ln x+1$","$\\frac1x$","$\\ln x$","$x$"],"c":0,"passos":["Pela regra do produto: $(x\\ln x)'=1\\cdot\\ln x+x\\cdot\\frac1x$.","Logo resulta $\\ln x+1$."],"fonte":"Ficha Derivadas"},
{"id":"r62","tema":"der","dif":"Médio","q":"Qual é a derivada de $\\sin(7x+2)$?","ops":["$\\cos(7x+2)$","$7\\cos(7x+2)$","$7\\sin(7x+2)$","$-7\\sin(7x+2)$"],"c":1,"passos":["Pela regra da cadeia, deriva-se o seno e multiplica-se pela derivada do argumento.","$[\\sin(7x+2)]'=\\cos(7x+2)\\cdot7$."],"fonte":"Ficha Derivadas"},
{"id":"r63","tema":"der","dif":"Médio","q":"Se $f(x)=x^2-\\frac14x$, qual é $f'(4)$?","ops":["$\\frac{15}{4}$","$\\frac{33}{4}$","$\\frac{31}{4}$","$\\frac{47}{4}$"],"c":2,"passos":["$f'(x)=2x-\\frac14$.","$f'(4)=8-\\frac14=\\frac{31}{4}$."],"fonte":"Ficha Derivadas"},
{"id":"r64","tema":"der","dif":"Médio","q":"A reta tangente a $f(x)=x^2-2x$ em $x=1$ é:","ops":["$y=x-1$","$y=-x+1$","$y=x+1$","$y=-1$"],"c":3,"passos":["$f'(x)=2x-2$, logo o declive em 1 é 0.","Como $f(1)=-1$, a tangente horizontal é $y=-1$."],"fonte":"Ficha Derivadas"},
{"id":"r65","tema":"der","dif":"Fácil","q":"Qual é o mínimo absoluto de $f(x)=x^2+1$?","ops":["1","0","$-1$","não existe"],"c":0,"passos":["$x^2\\ge0$ para todo o real.","Assim $x^2+1\\ge1$, com igualdade em $x=0$."],"fonte":"Ficha Derivadas"},
{"id":"r66","tema":"der","dif":"Difícil","q":"Qual é a derivada de $f(x)=\\frac{7}{5-7x}$?","ops":["$-\\frac{49}{(5-7x)^2}$","$\\frac{49}{(5-7x)^2}$","$\\frac7{(5-7x)^2}$","$\\frac{49}{5-7x}$"],"c":1,"passos":["Escreve-se $7(5-7x)^{-1}$.","A cadeia dá $7\\cdot(-1)(5-7x)^{-2}\\cdot(-7)=\\frac{49}{(5-7x)^2}$."],"fonte":"Ficha Derivadas"},
{"id":"r67","tema":"der","dif":"Médio","q":"Se $f(x)=x^3+3x^2$, qual é $f''(x)$?","ops":["$3x^2+6x$","$6x$","$6x+6$","$6x+3$"],"c":2,"passos":["$f'(x)=3x^2+6x$.","Derivando novamente, $f''(x)=6x+6$."],"fonte":"Ficha Derivadas"},
{"id":"r68","tema":"der","dif":"Difícil","q":"A função $f(x)=-x^2-2x+2$ tem máximo relativo em que ponto?","ops":["$(1,3)$","$(-1,-3)$","$(0,2)$","$(-1,3)$"],"c":3,"passos":["$f'(x)=-2x-2$ anula-se em $x=-1$ e muda de positivo para negativo.","$f(-1)=-1+2+2=3$, logo o máximo é $(-1,3)$."],"fonte":"Ficha Derivadas"},
{"id":"r69","tema":"pg","dif":"Fácil","q":"Numa PG, $u_1=4$ e $u_2=2$. Qual é o termo geral?","ops":["$u_n=4\\left(\\frac12\\right)^{n-1}$","$4\\left(\\frac12\\right)^n$","$2^n$","$4+\\frac n2$"],"c":0,"passos":["A razão é $r=\\frac24=\\frac12$.","Usa-se $u_n=u_1r^{n-1}$."],"fonte":"Prova modelo 2"},
{"id":"r70","tema":"pg","dif":"Médio","q":"Numa PA, $u_1=3$ e a razão é 5. Qual é $u_5$?","ops":["20","23","28","43"],"c":1,"passos":["Numa PA, $u_n=u_1+(n-1)r$.","$u_5=3+4\\cdot5=23$."],"fonte":"Ficha Sucessões"},
{"id":"r71","tema":"pg","dif":"Médio","q":"Numa PA, $u_6=10$ e $u_{12}=40$. Qual é a razão?","ops":["6","10","5","30"],"c":2,"passos":["A diferença é $u_{12}-u_6=6r$.","$40-10=6r$, logo $r=5$."],"fonte":"Ficha Sucessões"},
{"id":"r72","tema":"pg","dif":"Médio","q":"Numa PA, $u_1=-15$ e $r=5$. Qual é $u_6$?","ops":["15","5","20","10"],"c":3,"passos":["$u_6=u_1+5r$.","$-15+5\\cdot5=10$."],"fonte":"Ficha Sucessões"},
{"id":"r73","tema":"pg","dif":"Difícil","q":"Calcule a soma dos 14 primeiros termos da PA $1,5,9,\\ldots$.","ops":["378","364","392","196"],"c":0,"passos":["$u_{14}=1+13\\cdot4=53$.","$S_{14}=\\frac{14(1+53)}2=7\\cdot54=378$."],"fonte":"Ficha Sucessões"},
{"id":"r74","tema":"pg","dif":"Médio","q":"Numa PG de razão 2, sabe-se que $u_4=40$. Qual é $u_1$?","ops":["10","5","20","80"],"c":1,"passos":["$u_4=u_1\\cdot2^3=8u_1$.","$u_1=40/8=5$."],"fonte":"Ficha Sucessões"},
{"id":"r75","tema":"pg","dif":"Fácil","q":"Qual é a razão da PG $81,27,9,\\ldots$?","ops":["3","$-3$","$\\frac13$","$\\frac19$"],"c":2,"passos":["A razão é o quociente entre termos consecutivos.","$r=\\frac{27}{81}=\\frac13$."],"fonte":"Ficha Sucessões"},
{"id":"r76","tema":"pg","dif":"Difícil","q":"Numa PG, $u_2=12$ e $u_5=96$, com razão positiva. Determine $r$.","ops":["4","8","$\\sqrt2$","2"],"c":3,"passos":["$\\frac{u_5}{u_2}=r^3=\\frac{96}{12}=8$.","Como $r>0$, $r=2$."],"fonte":"Ficha Sucessões"},
{"id":"r77","tema":"pg","dif":"Médio","q":"Qual é a soma infinita $6+3+\\frac32+\\cdots$?","ops":["12","9","18","diverge"],"c":0,"passos":["É uma PG com $u_1=6$ e $r=\\frac12$, pelo que converge.","$S=\\frac6{1-\\frac12}=12$."],"fonte":"Ficha Sucessões"},
{"id":"r78","tema":"pg","dif":"Fácil","q":"Numa PA com $u_1=23$ e razão 5, qual é $u_5$?","ops":["28","43","38","48"],"c":1,"passos":["Em uma PA, $u_n=u_1+(n-1)r$.","$u_5=23+4\\cdot5=43$."],"fonte":"Ficha Sucessões"}
];

export const ABERTAS = [
{"id":"a1","tema":"comb","q":"No desenvolvimento de $(x-3)^7$, determine o termo de grau 5.","res":"O termo de grau 5 obtém-se escolhendo duas vezes $(-3)$: $^7C_2x^5(-3)^2=21\\cdot9x^5=189x^5$.","fonte":"Exame 2024"},
{"id":"a2","tema":"prob","q":"Uma fábrica A produz 70% das peças e B 30%; as taxas de defeito são 4% e 7%. Determine a probabilidade de uma peça defeituosa ter sido produzida em B.","res":"$P(D)=0,7\\cdot0,04+0,3\\cdot0,07=0,049$. Por Bayes, $P(B\\mid D)=\\frac{0,3\\cdot0,07}{0,049}=\\frac37\\approx42,9\\%$.","fonte":"Ficha Probabilidades"},
{"id":"a3","tema":"func","q":"Determine o vértice e o contradomínio de $f(x)=2x^2-12x+10$.","res":"$x_v=-\\frac{-12}{2\\cdot2}=3$ e $f(3)=-8$. Como $a=2>0$, o vértice é mínimo: $V=(3,-8)$ e $D'_f=[-8,+\\infty[$.","fonte":"Prova modelo 1"},
{"id":"a4","tema":"func","q":"A altura de um foguete é $h(t)=-t^2+16t-39$. Determine o instante e a altura máxima.","res":"$t_v=-\\frac{16}{2(-1)}=8$. Então $h(8)=-64+128-39=25$. A altura máxima é 25, atingida ao fim de 8 segundos.","fonte":"Ficha Funções"},
{"id":"a5","tema":"explog","q":"Resolva $\\log_2(5x+1)=4$.","res":"Pela definição, $5x+1=2^4=16$. Logo $x=3$. Verificação: $5\\cdot3+1=16>0$, portanto $S=\\{3\\}$.","fonte":"Ficha Exponenciais"},
{"id":"a6","tema":"explog","q":"Resolva $9^x=\\frac1{243}$.","res":"$9^x=3^{2x}$ e $\\frac1{243}=3^{-5}$. Pela injetividade da exponencial, $2x=-5$, logo $x=-\\frac52$.","fonte":"Ficha Exponenciais"},
{"id":"a7","tema":"trig","q":"Resolva $2\\sin x+1=0$ em $[0,2\\pi]$.","res":"$\\sin x=-\\frac12$. O seno é negativo nos quadrantes III e IV e o ângulo de referência é $\\frac\\pi6$. Assim, $x=\\frac{7\\pi}{6}$ ou $x=\\frac{11\\pi}{6}$.","fonte":"Ficha Trigonometria"},
{"id":"a8","tema":"trig","q":"Sabendo que $\\sin x=\\frac35$ e $x$ pertence ao segundo quadrante, determine $\\cos x$ e $\\tan x$.","res":"$\\cos^2x=1-\\frac9{25}=\\frac{16}{25}$. No segundo quadrante, $\\cos x=-\\frac45$. Então $\\tan x=\\frac{\\sin x}{\\cos x}=\\frac{3/5}{-4/5}=-\\frac34$.","fonte":"Ficha Trigonometria"},
{"id":"a9","tema":"lim","q":"Calcule $\\lim_{x\\to1}\\frac{x-1}{\\sqrt{x}-1}$.","res":"$x-1=(\\sqrt{x}-1)(\\sqrt{x}+1)$. Para $x\\ne1$, o quociente é $\\sqrt{x}+1$. Logo o limite é $1+1=2$.","fonte":"Ficha Limites"},
{"id":"a10","tema":"lim","q":"Determine $k$ para que $f(x)=\\begin{cases}kx+1,&x<2\\\\x^2-1,&x\\ge2\\end{cases}$ seja contínua em 2.","res":"À direita, e no valor da função, obtém-se $2^2-1=3$. À esquerda, o limite é $2k+1$. A continuidade exige $2k+1=3$, logo $k=\\frac12$.","fonte":"Ficha Limites"},
{"id":"a11","tema":"der","q":"Determine a reta tangente a $f(x)=x^2-3x$ no ponto de abcissa 2.","res":"$f'(x)=2x-3$, portanto o declive é $f'(2)=1$. O ponto é $(2,f(2))=(2,-2)$. Assim, $y+2=x-2$, isto é, $y=x-4$.","fonte":"Banco MatPrep"},
{"id":"a12","tema":"der","q":"Estude os extremos relativos de $f(x)=x^3+3x^2$.","res":"$f'(x)=3x(x+2)$, cujos zeros são $-2$ e 0. O sinal passa de positivo a negativo em $-2$: máximo $f(-2)=4$. Passa de negativo a positivo em 0: mínimo $f(0)=0$.","fonte":"Ficha Derivadas"},
{"id":"a13","tema":"pg","q":"Numa PA $4,8,12,\\ldots$, calcule a soma dos 13 primeiros termos.","res":"A razão é 4 e $u_{13}=4+12\\cdot4=52$. Portanto $S_{13}=\\frac{13(4+52)}2=13\\cdot28=364$.","fonte":"Ficha Sucessões"},
{"id":"a14","tema":"pg","q":"Numa PG de termos positivos, $u_2=12$ e $u_5=96$. Determine $u_1$ e a razão.","res":"$u_5/u_2=r^3=96/12=8$, pelo que $r=2$. Como $u_2=u_1r$, tem-se $12=2u_1$ e $u_1=6$.","fonte":"Ficha Sucessões"},
{"id":"a15","tema":"comb","q":"Uma aposta simples do Totoloto escolhe 5 números entre 49 e 1 estrela entre 13. Escreva a expressão que conta as apostas possíveis.","res":"Os 5 números são uma combinação, pois a ordem não conta: $^{49}C_5$. A estrela é escolhida de 13 formas: $^{13}C_1$. Pelo princípio multiplicativo, há $^{49}C_5\\cdot{}^{13}C_1$ apostas.","fonte":"Ficha Combinatória"},
{"id":"a16","tema":"prob","q":"Se $P(A)=0,5$, $P(B)=0,6$ e $P(A\\cup B)=0,8$, determine $P(A\\cap B)$ e $P(A\\mid B)$.","res":"$P(A\\cap B)=0,5+0,6-0,8=0,3$. Depois, $P(A\\mid B)=\\frac{0,3}{0,6}=0,5$.","fonte":"Exame 2022"},
{"id":"a17","tema":"func","q":"Determine o domínio de $f(x)=\\sqrt{x^2+x}$.","res":"É necessário $x^2+x=x(x+1)\\ge0$. Pelo estudo do sinal do produto, $x\\le-1$ ou $x\\ge0$. Assim, $D_f=]-\\infty,-1]\\cup[0,+\\infty[$.","fonte":"Ficha Funções"},
{"id":"a18","tema":"explog","q":"Resolva $2^{x+1}=8^{x-2}$.","res":"Como $8=2^3$, fica $2^{x+1}=2^{3x-6}$. Logo $x+1=3x-6$, isto é, $2x=7$ e $x=\\frac74$.","fonte":"Ficha Exponenciais"},
{"id":"a19","tema":"trig","q":"Resolva $\\cos x=-\\frac12$ em $[0,2\\pi]$.","res":"O ângulo de referência é $\\frac\\pi3$. Como o cosseno é negativo nos quadrantes II e III, as soluções são $\\frac{2\\pi}{3}$ e $\\frac{4\\pi}{3}$.","fonte":"Ficha Trigonometria"},
{"id":"a20","tema":"lim","q":"Calcule $\\lim_{x\\to0}\\frac{e^{-x}-1}{x}$.","res":"Faça-se $u=-x$. Então $\\frac{e^{-x}-1}{x}=-\\frac{e^u-1}{u}$. Como $\\lim_{u\\to0}\\frac{e^u-1}{u}=1$, o limite pedido é $-1$.","fonte":"Ficha Limites"},
{"id":"a21","tema":"der","q":"Determine $f'(x)$ para $f(x)=\\frac{7}{5-7x}$.","res":"$f(x)=7(5-7x)^{-1}$. Pela regra da cadeia, $f'(x)=7(-1)(5-7x)^{-2}(-7)=\\frac{49}{(5-7x)^2}$.","fonte":"Ficha Derivadas"},
{"id":"a22","tema":"pg","q":"Calcule a soma infinita $6+3+\\frac32+\\cdots$.","res":"É uma PG com primeiro termo 6 e razão $\\frac12$. Como $|r|<1$, converge e $S=\\frac{6}{1-1/2}=12$.","fonte":"Ficha Sucessões"}
];

export const MATERIAIS = [
{"id":"m1","tipo":"exercicio","tema":"comb","titulo":"TM Au 01 Combinatória 020","ficheiro":"TM Au 01 Combinatória 020.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m2","tipo":"exercicio","tema":"comb","titulo":"TM Au 01 Combinatória 030","ficheiro":"TM Au 01 Combinatória 030.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m3","tipo":"exercicio","tema":"comb","titulo":"TM Au 01 Combinatória Probabilidades - Ficha","ficheiro":"TM Au 01 Combinatória Probabilidades - Ficha.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m4","tipo":"exercicio","tema":"prob","titulo":"TM Au 01 Probabilidades 020","ficheiro":"TM Au 01 Probabilidades 020.pdf","video":{"id": "iNCkGogNtKI", "titulo": "Probabilidade — aprende em 13 min", "canal": "Sandro Curió"}},
{"id":"m5","tipo":"exercicio","tema":"func","titulo":"TM Au 02 Funções 001","ficheiro":"TM Au 02 Funções 001.pdf","video":{"id": "ZpW9Xb5iyt4", "titulo": "Função do 2.º grau — fácil e rápido", "canal": "Sandro Curió"}},
{"id":"m6","tipo":"exercicio","tema":"func","titulo":"TM Au 03 Funções 010 - Ficha","ficheiro":"TM Au 03 Funções 010 - Ficha.pdf","video":{"id": "ZpW9Xb5iyt4", "titulo": "Função do 2.º grau — fácil e rápido", "canal": "Sandro Curió"}},
{"id":"m7","tipo":"exercicio","tema":"trig","titulo":"TM Au 05 Funções Trigonométricas - Ficha","ficheiro":"TM Au 05 Funções Trigonométricas - Ficha.pdf","video":{"id": "OPsqOAgxR4g", "titulo": "Círculo trigonométrico — seno e cosseno", "canal": "Sandro Curió"}},
{"id":"m8","tipo":"exercicio","tema":"lim","titulo":"TM Au 06 Funções Limites Derivadas - Ficha","ficheiro":"TM Au 06 Funções Limites Derivadas - Ficha.pdf","video":{"id": "wPesFG0cG7g", "titulo": "Domínio de uma função real (base para limites)", "canal": "Sandro Curió"}},
{"id":"m9","tipo":"exercicio","tema":"der","titulo":"TM Au 07 Funções Derivadas 015","ficheiro":"TM Au 07 Funções Derivadas 015.pdf","video":{"id": "bZm6KZ_Cy2o", "titulo": "Equação reduzida da reta — declive (ideia de derivada)", "canal": "Sandro Curió"}},
{"id":"m10","tipo":"exercicio","tema":"der","titulo":"TM Au 07 Funções Derivadas 016","ficheiro":"TM Au 07 Funções Derivadas 016.pdf","video":{"id": "bZm6KZ_Cy2o", "titulo": "Equação reduzida da reta — declive (ideia de derivada)", "canal": "Sandro Curió"}},
{"id":"m11","tipo":"exercicio","tema":"pg","titulo":"TM Au 08 Funções Sucessões - Ficha","ficheiro":"TM Au 08 Funções Sucessões - Ficha.pdf","video":{"id": "haKrC4quHj8", "titulo": "Progressão geométrica — termo geral e soma", "canal": "Sandro Curió"}},
{"id":"m12","tipo":"teoria","tema":"comb","titulo":"TM Au 01 Combinatória 010","ficheiro":"TM Au 01 Combinatória 010.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m13","tipo":"teoria","tema":"comb","titulo":"TM Au 01 Combinatória 011","ficheiro":"TM Au 01 Combinatória 011.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m14","tipo":"teoria","tema":"prob","titulo":"TM Au 01 Probabilidades 012","ficheiro":"TM Au 01 Probabilidades 012.pdf","video":{"id": "iNCkGogNtKI", "titulo": "Probabilidade — aprende em 13 min", "canal": "Sandro Curió"}},
{"id":"m15","tipo":"teoria","tema":"func","titulo":"TM Au 02 Funções 000","ficheiro":"TM Au 02 Funções 000.pdf","video":{"id": "ZpW9Xb5iyt4", "titulo": "Função do 2.º grau — fácil e rápido", "canal": "Sandro Curió"}},
{"id":"m16","tipo":"teoria","tema":"func","titulo":"TM Au 02 Funções 010i","ficheiro":"TM Au 02 Funções 010i.pdf","video":{"id": "ZpW9Xb5iyt4", "titulo": "Função do 2.º grau — fácil e rápido", "canal": "Sandro Curió"}},
{"id":"m17","tipo":"teoria","tema":"func","titulo":"TM Au 02 Funções 011a","ficheiro":"TM Au 02 Funções 011a.pdf","video":{"id": "ZpW9Xb5iyt4", "titulo": "Função do 2.º grau — fácil e rápido", "canal": "Sandro Curió"}},
{"id":"m18","tipo":"teoria","tema":"explog","titulo":"TM Au 04 Exponenciais Logarítmicas 000","ficheiro":"TM Au 04 Exponenciais Logarítmicas 000.pdf","video":{"id": "tR6S4dz6UGA", "titulo": "Aprende logaritmo em 8 minutos", "canal": "Sandro Curió"}},
{"id":"m19","tipo":"teoria","tema":"trig","titulo":"TM Au 05 Trigonometria 000","ficheiro":"TM Au 05 Trigonometria 000.pdf","video":{"id": "OPsqOAgxR4g", "titulo": "Círculo trigonométrico — seno e cosseno", "canal": "Sandro Curió"}},
{"id":"m20","tipo":"teoria","tema":"lim","titulo":"TM Au 06 Limites e continuidade 000","ficheiro":"TM Au 06 Limites e continuidade 000.pdf","video":{"id": "wPesFG0cG7g", "titulo": "Domínio de uma função real (base para limites)", "canal": "Sandro Curió"}},
{"id":"m21","tipo":"teoria","tema":"lim","titulo":"TM Au 06 Limites e continuidade 015","ficheiro":"TM Au 06 Limites e continuidade 015.pdf","video":{"id": "wPesFG0cG7g", "titulo": "Domínio de uma função real (base para limites)", "canal": "Sandro Curió"}},
{"id":"m22","tipo":"teoria","tema":"der","titulo":"TM Au 07 Derivadas 000","ficheiro":"TM Au 07 Derivadas 000.pdf","video":{"id": "bZm6KZ_Cy2o", "titulo": "Equação reduzida da reta — declive (ideia de derivada)", "canal": "Sandro Curió"}},
{"id":"m23","tipo":"teoria","tema":"der","titulo":"TM Au 07 Derivadas 010","ficheiro":"TM Au 07 Derivadas 010.pdf","video":{"id": "bZm6KZ_Cy2o", "titulo": "Equação reduzida da reta — declive (ideia de derivada)", "canal": "Sandro Curió"}},
{"id":"m24","tipo":"teoria","tema":"der","titulo":"TM Au 07 Derivadas 015","ficheiro":"TM Au 07 Derivadas 015.pdf","video":{"id": "bZm6KZ_Cy2o", "titulo": "Equação reduzida da reta — declive (ideia de derivada)", "canal": "Sandro Curió"}},
{"id":"m25","tipo":"teoria","tema":"pg","titulo":"TM Au 08 Sucessões 010","ficheiro":"TM Au 08 Sucessões 010.pdf","video":{"id": "haKrC4quHj8", "titulo": "Progressão geométrica — termo geral e soma", "canal": "Sandro Curió"}},
{"id":"m26","tipo":"teoria","tema":"pg","titulo":"TM Au 08 Sucessões 020","ficheiro":"TM Au 08 Sucessões 020.pdf","video":{"id": "haKrC4quHj8", "titulo": "Progressão geométrica — termo geral e soma", "canal": "Sandro Curió"}},
{"id":"m27","tipo":"teoria","tema":"pg","titulo":"TM Au 08 Sucessões 030","ficheiro":"TM Au 08 Sucessões 030.pdf","video":{"id": "haKrC4quHj8", "titulo": "Progressão geométrica — termo geral e soma", "canal": "Sandro Curió"}},
{"id":"m28","tipo":"exame","tema":null,"titulo":"TM E20211215A","ficheiro":"TM E20211215A.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m29","tipo":"exame","tema":null,"titulo":"TM E20220119A","ficheiro":"TM E20220119A.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m30","tipo":"exame","tema":null,"titulo":"TM E20220124A","ficheiro":"TM E20220124A.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m31","tipo":"exame","tema":null,"titulo":"TM E20221123","ficheiro":"TM E20221123.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m32","tipo":"exame","tema":null,"titulo":"TM E20230111","ficheiro":"TM E20230111.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m33","tipo":"exame","tema":null,"titulo":"TM E20230116","ficheiro":"TM E20230116.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m34","tipo":"exame","tema":null,"titulo":"TM E20230130","ficheiro":"TM E20230130.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m35","tipo":"exame","tema":null,"titulo":"TM E20240122 Normal","ficheiro":"TM E20240122 Normal.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m36","tipo":"exame","tema":null,"titulo":"TM E20240205 Recurso","ficheiro":"TM E20240205 Recurso.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m37","tipo":"exame","tema":null,"titulo":"TM E20250212 Recurso","ficheiro":"TM E20250212 Recurso.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m38","tipo":"formulario","tema":null,"titulo":"TM Formulário","ficheiro":"TM Formulário.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m39","tipo":"exame","tema":null,"titulo":"TM Prova modelo 1","ficheiro":"TM Prova modelo 1.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m40","tipo":"exame","tema":null,"titulo":"TM Prova modelo 1 Resolvida","ficheiro":"TM Prova modelo 1 Resolvida.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}},
{"id":"m41","tipo":"exame","tema":null,"titulo":"TM Prova modelo 2","ficheiro":"TM Prova modelo 2.pdf","video":{"id": "f0OjyQhITv0", "titulo": "Análise combinatória — arranjo, permutação e combinação", "canal": "Sandro Curió"}}
];
